Crown-Commercial-Service/digitalmarketplace-user-frontend

- requirements-app.txt
- requirements.txt
- tests/main/views/test_auth.py
This PR will need merging first: [https://github.com/alphagov/digitalmarketplace-utils/pull/324](https://github.com/alphagov/digitalmarketplace-utils/pull/324)
Tokens have a lifespan of seven days. The new tokens include a `role`
key. We need to support the old style tokens until they are all no
longer valid.
> Support old tokens

- app/main/helpers/login_helpers.py
- tests/main/helpers/test_login_helpers.py
- tests/main/views/test_auth.py
- tests/main/views/test_create_user.py
After the buyer users have been added to the list of roles the prefix
checks no longer restrict protocol-relative URLs (eg //example.com),
allowing the login page to redirect the user to an external domain.
This is adding a `is_safe_url` function based on the one from
http://flask.pocoo.org/snippets/62/ (it's also used by Notify).
The function is modified to return `False` for empty target URLs.
This also removes per-role redirect restrictions since their original
purpose was to prevent the open redirects. User role now only affects
the default redirect location if next_url was not set, otherwise
next_url is used as is.
> Add a check for safe url for redirects after login

- app/main/views/auth.py
- app/main/views/reset_password.py
Part of this trello ticket: https://trello.com/c/HlSz9QZZ
Users who have locked their account can now reset it via the forgotten
password process. This means they no longer need to involve support.
These updated messages will encourage them to use this process and only
contact support if that doesn't work.
> Update message content for failed login and password reset

- requirements-app.txt
- requirements.txt
- tests/main/views/test_create_user.py
The latest version of utils removes a bit of code that deals with the case where tokens don't have a user role. The new way of generating tokens should have made that code obsolete, so this PR *shouldn't* break anything.
> Pull in latest utils

- requirements-app.txt
- requirements-dev.txt
- requirements.txt
- setup.cfg
Addresses a vulnerability in the Python `requests` library.
None of the breaking changes (direct awards, search_services, update_user) affect the User FE app.
Also fixes pytest deprecation warnings.
> Upgrade api client

- .flake8
- requirements-dev.txt
This allows us to use newer Python3 syntax including f-strings and type annotations.
```
samuelwilliams:~/git/digitalmarketplace-user-frontend [master]$ make test-flake8
[ -z $VIRTUAL_ENV ] && [ ! -d venv ] && virtualenv -p python3 venv || true
/Users/samuelwilliams/git/digitalmarketplace-user-frontend/venv/bin/flake8 .
./app/__init__.py:0:1: X100 Superfluous per-file-ignores for E402
make: *** [test-flake8] Error 1
```
> Change from flake8-putty to flake8-per-file-ignores

- app/main/views/reset_password.py
- config.py
- requirements-app.txt
- requirements.txt
- tests/main/views/test_auth.py
- tests/main/views/test_reset_password.py
https://trello.com/c/WTbemGdn/219-reset-password-emails-are-using-secretkey-instead-of-sharedemailkey-to-encrypt-tokens
Note, tests will likely fail until utils PR - https://github.com/alphagov/digitalmarketplace-utils/pull/354 - is merged and then pulled into this pull request.
We will be changing our tokens for reset password emails to be
generated using the `SHARED_EMAIL_KEY` rather than the `SECRET_KEY`.
This is because
- this will be consistent with the other email tokens we generate
- although there is technically no harm in using `SECRET_KEY`,
the actual purpose of the `SECRET_KEY` is to be used for encrypting
Flask sessions. This would mean if we needed to rotate a key for
our Flask sessions it would also break out email tokens and vice
versa. By using different keys we should …
> Use `SHARED_EMAIL_KEY` to encrypt reset password email tokens

- requirements-app.txt
- requirements.txt
Removes backwards compatability for old reset password tokens
that were using `SECRET_KEY` as their key rather than the
`SHARED_EMAIL_TOKEN` which is now used.
Note, must be deployed after 10/2/18 2pm so old tokens are given a full day to continue working before we remove compatibility for them.
> Pull in utils 32.0.0 to remove backwards compatibility for token

- app/main/views/auth.py
- tests/main/views/test_auth.py
Flask's `logout_user` does not clear all session variables: https://flask-login.readthedocs.io/en/latest/_modules/flask_login/utils.html#logout_user
This PR explicitly clears any session variables (e.g. set during supplier applications) immediately prior to logout.
> Clear session variables on logout

- requirements-app.txt
- requirements.txt
...and re-freeze requirements.txt. this should bring in the new request id header handling.
https://trello.com/c/dlbLmRDB/343-make-use-of-zipkin-headers-in-preference-to-request-id-pt-1
> request id handling: bump digitalmarketplace-utils dependency to 34.1.1

- app/main/views/status.py
- requirements-app.txt
- requirements.txt
The status endpoint for all of the apps is highly redundant across
repositories so I've moved it to dm-utils. We now only need to call this
method from the view stub in each app and pass in a couple of resources
(mainly the current_app and any api clients) to get a consistent status
JSON blob back.
https://trello.com/c/BBvu6eUk/383-ensure-healthcheck-endpoint-fails-if-low-disk-space
> Use centralised status method

- config.py
With load testing enabled the Gatling load tests won't work.
> Disable csrf on staging for loadtesting

- config.py
This should work fine as long as notify is using SES as their backend. if they change this, we just have to change this setting. using this has the advantage that it will appear to be "delivered" as far as notify's concerned and a record of the message's reference id will be kept.
> notify example redirection: switch the target email addresses to SES's equivalent simulated addresses

- tests/main/views/test_auth.py
- tests/main/views/test_create_user.py
- tests/main/views/test_notifications.py
- tests/main/views/test_reset_password.py
- tests/main/views/test_status.py
Following on from the Briefs FE test refactor (https://github.com/alphagov/digitalmarketplace-briefs-frontend/pull/93), refactoring to standardise test classes as follows:
- remove unnecessary `self.app.app_context` contexts (not required for FE app tests)
- `super(TestClassName, self)` ---> `super()` for Python 3
- patch Data API client at setup/teardown level instead of decorators, to tidy parameters and avoid accidentally patching a single API method rather than the whole API.
- ensuring `teardown()` methods include `super()` 
The `TestUserResearchNotifications` class uses functions that import the API from two modules (`auth.py` and `notifications.py`), so two patches are required.
> Refactor User FE tests

- app/main/forms/auth_forms.py
- app/main/views/reset_password.py
- app/templates/auth/change-password.html
- requirements-app.txt
- requirements.txt
- tests/main/views/test_reset_password.py
Trello: https://trello.com/c/TieWrBG5/44-password-reset-link-from-logged-in-session
Following QA of the change password form on preview. The error fields in the validation masthead now match the ordering of the form fields.
This requires adding a numbered prefix to the field's `id`, so we can sort non-alphabetically. WTForms doesn't seem to have a specific sort order functionality - it relies on declaration order, but we're subclassing another form so the ordering is jumbled. This doesn't seem ideal, any suggestions welcome.
Also pulls in updated utils, which fixes a small bug in the password reset token decoding (see https://github.com/alphagov/digitalmarketplace-utils/pull/392).
> Validation masthead error message ordering should match fields

- app/templates/auth/change-password.html
- app/templates/auth/reset-password.html
Trello: https://trello.com/c/TieWrBG5/44-password-reset-link-from-logged-in-session
Following a requested content change on the password change form to remove hint text - previously was `Repeat password used above`. I've updated the password reset form where this was copied from as well:
> Change password hint text wording

- app/main/views/notifications.py
Changes
Cookie banner to appear on all pages for logged in and logged out users until they click close or opt in. If clicked close, it reappears after 90 days.
Ticket: https://trello.com/c/48pZNhaG/120-iterate-opt-in-flow-for-user-research-participants
> Decrease cookie expiry to 90 days

- app/main/forms/auth_forms.py
- app/main/views/auth.py
- app/main/views/create_user.py
- app/main/views/notifications.py
- app/main/views/reset_password.py
- app/templates/auth/change-password.html
- app/templates/auth/create-user.html
- app/templates/auth/login.html
- app/templates/auth/reset-password.html
- app/templates/notifications/user-research-consent.html
- package.json
- requirements-app.txt
- requirements.txt
- tests/main/views/test_reset_password.py
- yarn.lock
Use validation masthead from the frontend-toolkit consistently.
Also converts most pages over to using the base page from the frontend-toolkit.
https://trello.com/c/RSYEM3FL/448
https://github.com/alphagov/digitalmarketplace-frontend-toolkit/pull/440
> Consolidate validation mastheads

- app/templates/errors/400.html
This brings the content in line with the other custom 400 error pages in
the buyer and supplier frontends.
> Update content for 400 error page

- package.json
- yarn.lock
Includes user research banner CSS tweaks from alphagov/digitalmarketplace-frontend-toolkit#446
> Update frontend-toolkit to v31.2.0

- Dockerfile
- app/main/forms/auth_forms.py
- requirements-app.txt
- requirements.txt
A double bump here.
This should allow zipkin logging to work better in both the nginx and app logs and also fix a medium security issue.
> Bump utils & docker base

- app/templates/auth/create-user.html
- app/templates/auth/login.html
I thought we'd done this already as part of Sam's refactoring ticket (https://trello.com/c/RSYEM3FL/448-validation-mastheads-should-use-toolkit-template), but it seems not.
There's no spacing between the header and the masthead on these pages, because there are no breadcrumbs (the user is logged out so we can't really have `Digital Marketplace > Your Account`). This is the current situation in production, i.e. this PR is not visually worse than the status quo 😸
> Use validation template

- requirements-app.txt
- requirements.txt
This should bring `childSpanId` logging.
> digitalmarketplace-apiclient dependency: bump to 17.4.0

- app/main/errors.py
As per: https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/828 
Fixes bug in production where API client errors were not being handled correctly.
BAD:
```
render_error_page(400)
```
GOOD:
```
render_error_page(status_code=400)
```
> User FE errors: Pass error status code as kwarg

- app/__init__.py
- app/main/views/auth.py
- package.json
- requirements-app.txt
- requirements.txt
- tests/test_application.py
- yarn.lock
Trello: https://trello.com/c/euSnpBnN/65-update-flask-login
Changelog: https://github.com/maxcountryman/flask-login/blob/master/CHANGES
The only breaking change that affects the User FE is the `current_user.is_authenticated` method is now an attribute. As well as a check on the login page, we also use it to conditionally render certain links in the template header (hence the FE toolkit update).
Tested locally, it seems fine with other apps still on Flask-Login 0.2.x and the old templates.
We were also arbitrarily mocking `is_authenticated` in the error handling tests to make a view (any view!) raise an exception. Rather than fiddling about to make an mocked attribute have a side effect, I've just used a different function (`get_errors_from_wtform`) instead. We're not testing that view or …
> User FE: Update Flask-Login to 0.4.x

- app/__init__.py
- config.py
- requirements-app.txt
- requirements.txt
Trello https://trello.com/c/ZH9trgjH/419-snyk-alert-for-flask-010x-vulnerability
https://github.com/alphagov/digitalmarketplace-utils/pull/447
Another bog standard conversion now that @katstevens has got her merge in.
> digitalmarketplace-utils: bump to 43.0.0, remove featureflags references

- app/main/views/reset_password.py
- config.py
- tests/main/views/test_reset_password.py
https://trello.com/c/ARkdAn0z
Depends on https://github.com/alphagov/digitalmarketplace-utils/pull/500
At token generation time, if the user turns out to be inactive, instead of sending a password reset token we send the user a message explaining that their account is disabled and what they can do about it.
~Still to do: decide on the content of this message, write the Notify template and paste its template id in to the `config`.~
~Edit: oh and write some functional tests.~
> password reset mechanism: handle inactive users more gracefully

- requirements-app.txt
- requirements.txt
- tests/main/views/test_auth.py
- tests/test_application.py
https://trello.com/c/9l0YBPl5
Also bump `digitalmarketplace-content-loader` to `5.2.1` and other version bumps that come with the re-freeze.
This includes werkzeug 0.15, which requires a couple of minor changes to our tests that depend on the default behaviour of werkzeug/flask, which has changed but not in a way that I think is particularly important to us.
To make it clear that one of the tests is simply being affected by the change in default base path for absolutizing url redirects (and has nothing to do with `@` handling) I added another test which simply exhibits the path absolutizing on its own.
The "default default" redirect code has also changed to 308, which I've reflected in a single test change.
> Bump digitalmarketplace-utils dependency to v48.2.0

- Dockerfile
Bumping this to the latest release so we get security updates etc.
> docker base image dependency: bump to 4.5.4

- app/main/views/create_user.py
- app/main/views/reset_password.py
- app/templates/auth/create-user-error.html
- config.py
- tests/helpers.py
- tests/main/views/test_create_user.py
- tests/main/views/test_reset_password.py
https://trello.com/c/3om47rfx/601-update-remaining-instances-of-enquiriesdigitalmarketplaceservicegovuk-to-the-new-support-address
Centralises the support email rather than hardcoding it in:
- create user templates/flash messages
- reset password templates/flash messages (see below)
> Move support email to app config

- app/main/views/reset_password.py
- tests/main/views/test_reset_password.py
Trello: https://trello.com/c/lkytm0e1/604-disable-the-password-reset-mechanism-for-the-admin-manager
> Disallow admin-manager from using password reset

- app/main/views/reset_password.py
- tests/main/views/test_reset_password.py
https://trello.com/c/o7nrGSfH
Without a comma this is just interpreted as a set of ignorable brackets.
Also improved the tests around this. This is a perfect example of why "one test, one feature" doesn't cut it.
> send_reset_password_email: fix check of user.role being "admin-manager" 

- config.py
- default.nix
https://trello.com/c/HsZ9mj7o
This should only ever show itself in place of a CSRF token failure, so should be a fairly safe thing to enable.
> set DM_COOKIE_PROBE_COOKIE_EXPECT_PRESENT, enabling cookie error page 

- gulpfile.js
- package-lock.json
- package.json
Introduces Standard JS for linting but only checks gulpfile.js. If you run npx standard you will see all the other files that fail Standards rules. We have decided not to address all the other javascript files at this point as we feel it would be better to look at them when we come to updating the javascript and using GOV.UK Frontend.
Trello Card: https://trello.com/c/ZkJAWEnM
> Add Standard JS

- app/data/password_blacklist/10-million-password-list-top-100000.txt
This password is used in some tests and consequently was causing failures.
> Remove password used in tests

- app/main/views/reset_password.py
- requirements-dev.txt
- tests/main/views/test_reset_password.py
Trello: https://trello.com/c/PTzPDEqq/1166-address-user-enumeration-forgot-pw-function-vulnerability
Addresses the scenario where an attacker could determine the existence of an account by looking at the response time from the password reset view. To mitigate this, the view should do roughly the same actions for a non-existent user as for an existing inactive user. Local timing testing is always going to be a bit unreliable in terms of network requests so I'd like to see how this does on Preview before releasing.
Agreed with the Notify team that the sandbox email address is suitable for this usecase.
I also tidied up the tests for this view, as it was hard to tell what paths had coverage.
> Password reset sends sandbox email for nonexistent accounts

- app/main/views/auth.py
- tests/main/views/test_auth.py
We might want to be able to create a link to logout a user using the `<a>` HTML tag. I've created this PR as a strawman that we can discuss.
In our current frontend apps we use a form to ask the browser to make a POST request to the logout url. This has some advantages on the backend (it's clear that the request is destructive, we can include a CSRF token), but on the frontend this causes issues with the log out button.
In the current admin frontend the focus state of a form differs visually from the focus state of a link.
With the GOV.UK Frontend, this problem is exacerbated as currently the header component does not support arbitrary HTML, and the form styles are designed for multiple inputs, not just one button.
These issues with the focus state might not be easy to fix if we continue …
> Allow visiting `/users/logout` with a GET request

- app/templates/_base_page.html
- app/templates/auth/change-password.html
- app/templates/auth/create-user-error.html
- app/templates/auth/create-user.html
- app/templates/auth/login.html
- app/templates/auth/request-password-reset.html
- app/templates/auth/reset-password.html
- app/templates/notifications/user-research-consent.html
https://trello.com/c/PpFz5qRc/43-create-a-base-page-for-the-apps
The work to move to govuk-frontend will be easier if we have a base page in each app in which to import macros.
GOVUK Frontend may solve this down the road
https://github.com/alphagov/govuk-frontend/issues/1278
It seems from research (Googling and GOV Pay) for now this is the accepted pattern
> 43-create-a-base-page-for-the-apps

- app/templates/_base_page.html
- app/templates/auth/change-password.html
- app/templates/auth/login.html
- app/templates/auth/request-password-reset.html
- app/templates/auth/reset-password.html
- app/templates/notifications/user-research-consent.html
- tests/helpers.py
- tests/main/views/test_reset_password.py
https://trello.com/c/vcjVUo8x
In places where we didn't previously have a trailing breadcrumb element representing the current page I added one, mostly with the exact heading of the page but in some places using a bit of artistic license to make it a bit simpler (see user research mailing list page).
> switch to using digitalmarketplace-govuk-frontend for breadcrumbs, standardize trailing breadcrumb element

- package-lock.json
- package.json
https://trello.com/c/aQbqH2uC/1196-vulnerability-fix-weekly-tracking
Addressing https://app.snyk.io/vuln/npm:jquery:20150627 and https://app.snyk.io/vuln/SNYK-JS-JQUERY-174006
The User FE only uses jquery in a couple of unit tests for the analytics functions. If those tests are later centralised in the FE toolkit, we can remove this dependency.
> Bumps jquery from 1.12 to 3.4.1

- app/assets/javascripts/application.js
The AJAX calls in this module were giving Javascript errors after we [bumped jquery to v3](https://github.com/alphagov/digitalmarketplace-user-frontend/pull/168), causing our Capybara tests to fail:
```
https://www.preview.marketplace.team/user/static/javascripts/application.js?28b93c55c2e834a461825f454eae7148:1 in handle (Capybara::Poltergeist::JavascriptError)
```
> [Fix] Remove unused live-search.js from User FE

- app/assets/scss/application.scss
- app/assets/scss/overrides/_notification-banner.scss
There is a current issue with vertical spacing of notifications. This
commit adds it temporarily but idealy the component itself should be
adding the margin spacing it requires.
> Adding vertical spacing to notifications.

- gulpfile.js
Fixing a bug with the build process where fonts were not being copied to
the correct path. This is not an issue at the moment because we are still
using govuk_template but once we migrate to govuk-frontend then it would
become a problem
Ticket: https://trello.com/c/HDc1fOJp
> Copy fonts to static folder

- app/templates/_base_page.html
- app/templates/auth/change-password.html
- app/templates/auth/create-user-error.html
- app/templates/auth/create-user.html
- app/templates/auth/login.html
- app/templates/auth/request-password-reset.html
- app/templates/auth/reset-password.html
- app/templates/notifications/user-research-consent.html
As part of migrating us off govuk_template and on to govuk frontend template
we need to be mindful of what blocks govuk frontend uses. govuk frontend
template uses pageTitle so instead of adding this commit to that work it
can be done as a separate commit and then once we come to replace govuk_template
we can just remove the two lines of code in `_base_page` which we added
in this commit.
Ticket: https://trello.com/c/R7sypvUC
> replace page_title block with pageTitle

- app/templates/_base_page.html
- app/templates/auth/change-password.html
- app/templates/auth/create-user-error.html
- app/templates/auth/create-user.html
- app/templates/auth/login.html
- app/templates/auth/request-password-reset.html
- app/templates/auth/reset-password.html
- app/templates/notifications/user-research-consent.html
As part of migrating us off govuk_template and on to govuk frontend template
we need to be mindful about what blocks govuk frontend uses. govuk frontend
template uses content block so instead of adding this commit to that work it
can be done as a separate commit and then once we come to replace govuk_template
we can just remove the `main_content` block of code and leave mainContent block in `_base_page`.
We will need to output flash messaging inside the content block so we cannot just use govuk-frontend template's `content` block to render our page.
Ticket: https://trello.com/c/sTPVOIu2
> replace main_content block with mainContent

- config.py
- package-lock.json
- package.json
Updates digitalmarketplace-govuk-frontend to 0.2.1 which fixes and issue with error pages.
Ticket https://trello.com/c/T9hBnYM5
> Updates digitalmarketplace-govuk-frontend to 0.2.1

- app/assets/scss/application.scss
We are no longer using the dmspeak classes so we should remove the import.
> Removes dmspeak import from application.scss

- app/assets/scss/_error-pages.scss
- app/assets/scss/application.scss
The application is now using digitalmarketplace-govuk-frontend error page
template. We have also removed dmspeak so this would not output anything.
> Remove error-page styling

- app/assets/javascripts/application.js
- app/templates/_base_page.html
- app/templates/auth/change-password.html
- app/templates/auth/create-user.html
- app/templates/auth/login.html
- app/templates/auth/request-password-reset.html
- app/templates/auth/reset-password.html
- app/templates/notifications/user-research-consent.html
- requirements-app.txt
- requirements.txt
Requires https://github.com/alphagov/digitalmarketplace-utils/pull/543 to be merged and for this repo to be updated to use the changes.
Ticket: https://trello.com/c/jy1qTEQN/132-replace-validation-banner-with-govuk-frontend-error-summary-component-in-user-frontend
> Replace Validation component with GOV.UK Error Summary

- .travis.yml
- requirements-app.txt
- requirements-dev.txt
- requirements.txt
https://trello.com/c/GsDBHBo7/135-switch-on-python-37-and-38-travis-checks-to-check-potential-dependency-problems-before-upgrade
- Bumps content loader, test utils and API client (utils already bumped)
- Adds 3.7 and 3.8 to Travis config
> Enable Python 3.7 & 3.8 Travis checks

- app/assets/scss/application.scss
- app/assets/scss/overrides/_govuk-label.scss
- app/templates/_base_page.html
- app/templates/auth/change-password.html
- app/templates/auth/create-user.html
- app/templates/auth/login.html
- app/templates/auth/request-password-reset.html
- app/templates/auth/reset-password.html
- tests/main/views/test_reset_password.py
We should be able to use `govuk-frontend` input component. This
replaces `digitalmarketplace-frontend-toolkit` textbox component.
We still need to decide whether we still want to have bold and slightly
larger labels compared to govuk-frontend default.
Ticket: https://trello.com/c/aSN47QjR
> Update textboxes to use GOV.UK Frontend text input component

- app/templates/auth/create-user-error.html
Removes explanation list and large style paragraph.
Counterpart of https://github.com/alphagov/digitalmarketplace-briefs-frontend/pull/249/commits/121a7e0f3020aaa2e380f8fc1bf2dcf1e7c00d47
> Simplify layout of create buyer user invalid domain error text

- app/templates/auth/change-password.html
- app/templates/auth/create-user.html
- app/templates/auth/login.html
- app/templates/auth/request-password-reset.html
- app/templates/auth/reset-password.html
- tests/main/views/test_auth.py
- tests/main/views/test_create_user.py
- tests/main/views/test_reset_password.py
Ticket: https://trello.com/c/9Swa9RO1/167-3-remove-autocomplete-off-from-our-login-page
WCAG 2.1 requires that forms fields specify their input purpose [[1]].
[1]: https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose.html
> Add autocomplete to forms and fields

- .dependabot/config.yml
I would like to try using [Dependabot](https://dependabot.com) with a frontend repo, as we have been having issues with PyUp recently. This PR is an experiment, I expect that it will either be superseded or reverted at a later date.
This PR adds a [Dependabot config file](https://dependabot.com/docs/config-file/) that I think should cause Dependabot to update requirements in `requirements.txt` weekly. Unfortunately the configuration for Dependabot doesn't seem to be as flexible as PyUp's. I can't see a way to specify filenames using the Dependabot config file format; there might be a way to do so in the GUI, I'm not sure.
On the plus side for Dependabot, we could use it to manage both Python and JavaScript dependencies. Also, Dependabot claims that its [Python …
> Try Dependabot

- package-lock.json
- package.json
Ticket: https://trello.com/c/i4eJBbNC/274-replace-content-supplier-a-z-with-supplier-a-to-z
Updates digitalmarketplace-govuk-frontend from 0.3.1 to 0.4.1, pulling in the new footer.
> Update link text for 'G-Cloud supplier A to Z' for footer link

- app/assets/javascripts/application.js
- app/assets/scss/application.scss
- app/assets/scss/overrides/_cookie-settings.scss
- app/assets/scss/overrides/_govuk-label.scss
- app/main/__init__.py
- app/main/views/cookie_settings.py
- app/templates/_base_page.html
- app/templates/cookies/cookie_settings.html
- package-lock.json
- package.json
- requirements.in
- requirements.txt
- tests/main/views/test_cookie_settings.py
https://trello.com/c/hGlNERQ6/294-cookie-settings-page
Adds new page for a user to set their cookie preferences, via the client side. 
Test coverage here: https://github.com/alphagov/digitalmarketplace-functional-tests/pull/733
Pulls in https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/63
> Cookie settings page

- package-lock.json
- package.json
Snyk reported a [vulnerability on kind-of >=6.0.0<6.0.3][1].
I updated it by running `npm update --depth 5 kind-of`.
[1]: https://app.snyk.io/vuln/SNYK-JS-KINDOF-537849
> Update kind-of from 6.0.2 to 6.0.3

- package-lock.json
- package.json
Ticket: https://trello.com/c/0PYrZ8Yy/323-cookie-settings-form-defaults-to-no-even-if-preference-set-to-yes
> Update digitalmarketplace-govuk-frontend from 0.6.0 to 0.6.1

- package-lock.json
- package.json
[No ticket]
Pulls in the fix for the Analytics tracking ID: https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/71
> Update Analytics tracking ID

- package-lock.json
- package.json
https://trello.com/c/feRizfhu/326-analytics-tracking-id-fix
Analytics was only being initialised when a user set or changed their preferences. Subsequent pageviews were not triggering an analytics request.
`all.js` now checks for a consent cookie, and initialises analytics if consent has been given.
> Pull in analytics initialisation

- config.py
https://trello.com/c/085wlnUP
This was presumably disabled to allow gatling scripts to run, but we now have a mechanism in place that allows gatling to work properly with csrf.
> config: re-enable WTF_CSRF_ENABLED for staging

- package-lock.json
- package.json
https://trello.com/c/JNW4K4vr/1618-vulnerability-fix-tracking
The dependency was actually removed in https://github.com/alphagov/digitalmarketplace-user-frontend/pull/204, but not from `package.json`.
This supersedes the Snykbot PR https://github.com/alphagov/digitalmarketplace-user-frontend/pull/251.
> Remove jQuery

- Makefile
When running `dm-runner` on a clean machine I got the following error:
```
17:15:07            user-frontend | npm run --silent frontend-build:development
17:15:09            user-frontend | [17:15:09] Local modules not found in ~/git/digitalmarketplace-user-frontend
17:15:09            user-frontend | [17:15:09] Try running: npm install
```
This is because the Makefile previously did not call the `npm-install` step.
This PR changes the task to call `npm-install` also changes the command to be consistent with supplier-frontend by using `npm ci`
as per: https://github.com/alphagov/digitalmarketplace-supplier-frontend/blob/01b32bb756541b3aa2e52c949a0de4a351ddda64/Makefile#L40-L41
> use npm install step in Makefile

- app/assets/scss/overrides/_cookie-settings.scss
- app/templates/cookies/cookie_settings.html
- tests/main/views/test_cookie_settings.py
Add [error summary component](https://design-system.service.gov.uk/components/error-summary/)  link.
This is part of: https://trello.com/c/btdB5xBK/98-missing-contextual-error-messaging-on-cookie-settings-page
> add link to error summary box

- package-lock.json
- package.json
required for https://trello.com/c/btdB5xBK/98-missing-contextual-error-messaging-on-cookie-settings-page
> bump digitalmarketplace-govuk-frontend version

- app/templates/auth/create-user.html
We should [disable HTML5 validation](https://design-system.service.gov.uk/patterns/validation/) from forms wherever possible and display our own error messages.
> Add novalidate attribute to create user form

- Dockerfile
bump docker image version to pick up changes from https://github.com/alphagov/digitalmarketplace-docker-base/pull/74
> bump docker base version number

- package-lock.json
- package.json
I created a new pre-release of digitalmarketplace-govuk-frontend with govuk-frontend v3, bringing in changes from release 1.0.1 of the main branch.
To do this I did the following:
git checkout govuk-frontend-3
git merge master
git commit package/package.json
git push origin govuk-frontend-3
npm run release-to-branch
git tag pre-release-v2.0.0-govuk-frontend-3-r2
git push --tags
> Bump digitalmarketplace-govuk-frontend to 2.0.0-govuk-frontend-3-r2

- .gitignore
- app/assets/javascripts/application.js
- app/assets/scss/application.scss
- app/templates/cookies/cookie_settings.html
- config.py
- gulpfile.js
- package-lock.json
- package.json
https://trello.com/c/fhL8Zl8T/175-3-unbundle-govuk-frontend-from-digitalmarketplace-govuk-frontend
digitalmarketplace-govuk-frontend has been updated so that it is no longer bundled with govuk-frontend.
This PR addresses those changes.
> Install digitalmarketplace-govuk-frontend and govuk-frontend separately

- app/main/views/auth.py
- app/templates/_base_page.html
- tests/main/views/test_auth.py
https://trello.com/c/S54PAyW3/214-fix-error-messages-on-login-page-to-resolve-audit-issue
This PR improves the experience when a user enters the wrong credentials. Currently, we display a flash with an error message, which isn't the most helpful for e.g. screen readers.
Replace this with an error summary that instructs users to check their email and password and links to both fields.
New:
> Update error message on login

- package-lock.json
- package.json
https://trello.com/c/OBFVKC3p/241-1-bump-govuk-frontend-to-391-on-briefs-and-user
We need to bump govuk-frontend to 3.9.1 to fix an accessibility bug:
https://github.com/alphagov/govuk-frontend/releases/tag/v3.9.1
> Bump govuk-frontend to 3.9.1

- requirements.in
Noticed this whilst working on another story. This repo is missing the instruction note for requirements we include in other repos.
> add instruction note

- app/main/views/auth.py
- app/templates/_base_page.html
- app/templates/auth/login.html
- tests/main/views/test_auth.py
- Add logic for the banner
- Add tests for the banner
This is from the ticket [OST-134](https://crowncommercialservice.atlassian.net/browse/OST-134) (3/5)
This is a screenshot of what the login page would look like:
I've set it up so the the banner will be shown on and after the DOS6 'Go Live' date (2022-01-14).
In order to see the banner before the 'Go Live' date, a user can add the param `show_dmp_so_banner=true` to the URL.
So for preview, the url to view the banner now would be: https://www.preview.marketplace.team/user/login?show_dmp_so_banner=true
> Add the notification banner 
