Crown-Commercial-Service/digitalmarketplace-user-frontend

app/assets/scss/application.scss

I forgot to import the scss for the proposition header. The logout
button looks like a button without it. We don't want that. We want it to
look like a link. Even though it's a button.

Import scss for proposition header.

---

app/templates/auth/create-user.html
tests/main/views/test_create_user.py

Story https://trello.com/c/fNL5RPyB/81-update-the-create-account-page-to-remove-the-word-contributor-1
Now this looks like

create_user template: modify displayed text

---

app/assets/scss/_text.scss
app/assets/scss/application.scss
app/main/__init__.py
app/main/views/notifications.py
app/templates/notifications/user-research-consent.html
package.json
tests/helpers.py
tests/main/views/test_notifications.py
yarn.lock

As a developer I need to be able to use a form for validating responses to the sign me up for user research page.
This form should follow existing pattens so it is easily extensible.
See prototype for fields and help text
Ticket: https://trello.com/c/qoRyFSEn/130-backend-form-for-sign-up-to-mailing-list

Backend form for sign up to mailing list

---

app/main/helpers/login_helpers.py
app/main/views/create_user.py
tests/main/views/test_create_user.py

Trello: https://trello.com/c/NwUPIHIb/413-flash-messages-user-app
This will enable the Supplier and Buyer apps to use the new style flash message to track page views (see https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/845 for discussion).

Convert 'flag' flash message to 'track-page-view'

---

app/main/forms/user_research.py
app/main/views/notifications.py
app/templates/notifications/user-research-consent.html
tests/main/views/test_notifications.py

Use a WTform for the user research opt int as per @TheDoubleK s comments
Adding a couple of tests now

WTForm for user research opt in

---

app/__init__.py
app/main/forms/auth_forms.py
app/main/forms/user_research.py
requirements-app.txt
requirements.txt

This includes fixes for security issues https://snyk.io/vuln/SNYK-PYTHON-BOTO3-40617 and https://snyk.io/vuln/SNYK-PYTHON-WTFORMS-40581, the fix for the latter requiring a synchronized rollout across all frontends

digitalmarketplace-utils dependency: bump to 36.2.2

---

app/main/forms/auth_forms.py
app/main/helpers/logging_helpers.py
app/main/helpers/login_helpers.py
app/main/views/notifications.py
app/main/views/reset_password.py
app/templates/auth/change-password.html
app/templates/auth/create-user.html
app/templates/auth/login.html
app/templates/auth/reset-password.html
config.py
requirements-app.txt
requirements.txt
tests/helpers.py
tests/main/views/test_reset_password.py

Following our security report recommendation (see ticket for link to report)
The Trello ticket: https://trello.com/c/TieWrBG5/44-password-reset-link-from-logged-in-session

Enable users to change their password when logged in

---

app/main/views/auth.py

API pull request: https://github.com/alphagov/digitalmarketplace-api/pull/799
Trello ticket: https://trello.com/c/alSuFp7x/457-give-users-10-password-attempts

Update validation message for failed login attempt as user has 10 attempts now

---

app/assets/javascripts/application.js

This commit completes the [roll out of the feedback form][ticket] to this app by adding the required javascript.
[ticket]: https://trello.com/c/m9onh6tC

Add report-a-problem.js to the application

---

app/main/views/reset_password.py
requirements-app.txt
requirements.txt
tests/main/views/test_reset_password.py

Upgrade to flask 1.0.2
https://trello.com/c/bBDir2Gp/18-flask-1x-upgrade

Upgrade to flask 1.0.2

---

app/__init__.py
app/metrics.py
requirements-app.txt
requirements.txt
tests/helpers.py
tests/test_metrics.py

* Add dependencies
* Add metrics
* Add tests
https://trello.com/c/Fqq8RCEb/495-add-metrics-to-briefs-user-and-admin-frontends

495-add-metrics-to-briefs-user-and-admin-frontends

---

requirements-app.txt
requirements.txt
tests/main/views/test_auth.py

https://trello.com/c/HsZ9mj7o
Also modify some tests to cope with newly set "probe cookie" for detecting cookie-disabled browsers.

cookie-probe: bump digitalmarketplace-utils dependency to 48.5.0

---

app/assets/scss/application.scss
app/assets/scss/overrides/_page_headings.scss
app/templates/auth/change-password.html
app/templates/auth/create-user-error.html
app/templates/auth/create-user.html
app/templates/auth/login.html
app/templates/auth/request-password-reset.html
app/templates/auth/reset-password.html
app/templates/notifications/user-research-consent.html

switch headings to digitalmarketplace-govuk-frontend, add temp spacing override

---

app/assets/scss/application.scss
app/templates/auth/change-password.html
app/templates/auth/create-user.html
app/templates/auth/login.html
app/templates/auth/request-password-reset.html
app/templates/auth/reset-password.html
app/templates/notifications/user-research-consent.html

https://trello.com/c/1jazDBYI
Plus one place I did a bit of indentation fixing.

switch buttons to digitalmarketplace-govuk-frontend

---

app/main/views/create_user.py
app/templates/auth/create-user-error.html
app/templates/auth/request-password-reset.html
app/templates/auth/reset-password.html
app/templates/notifications/user-research-consent.html
tests/main/views/test_auth.py
tests/main/views/test_create_user.py

switch paragraphs, links and lists to digitalmarketplace-govuk-frontend's classes

---

app/assets/scss/application.scss
app/templates/auth/change-password.html
app/templates/auth/login.html
app/templates/notifications/user-research-consent.html

trello: https://trello.com/c/QS7XZ69i/144-3-remove-secondary-action-link-component-from-user-frontend

removed secondary-action-link for user FE

---

app/main/views/reset_password.py
config.py
requirements.in
requirements.txt
tests/main/views/test_auth.py
tests/main/views/test_create_user.py
tests/main/views/test_reset_password.py

Simple https://trello.com/c/AVadfnPO

config: rename *_SALT variables to the newer more accurate *_TOKEN_NS

---

app/main/forms/auth_forms.py
app/templates/auth/create-user.html
tests/main/views/test_create_user.py
tests/main/views/test_reset_password.py

https://trello.com/c/Yy3pBfww/13-1-review-error-messages-for-create-a-buyer-account-journey-in-briefs-frontend
Update the form error messages on /user/create/<token> to follow [GOV.UK Design System guidance](https://design-system.service.gov.uk/components/error-message/#be-clear-and-concise).

Review error messages for /user/create/<token>

---

package-lock.json
package.json

https://trello.com/c/FR1sGM3j/22-2-fix-axe-errors-in-digitalmarketplace-govuk-frontend

Bump DM-govuk-frontend to 0.9.0

---

requirements.in
requirements.txt

to pull in changes for https://trello.com/c/PTdD5lEh/102-our-logs-show-paas-instance-guid-but-not-paas-instance-index

bump utils library

---

package-lock.json

Update lodash node-sass and yargs-parser with npm audit

---

app/templates/_base_page.html
package-lock.json
package.json

https://trello.com/c/N0tUjqnr/265-2-set-active-styles-on-header-nav-links

Add active links to the header

---

requirements.in
requirements.txt

https://trello.com/c/XXL04KtG/379-3-run-the-new-user-session-management-on-the-local-development-environment
N.B. this is preparatory and should not affect behaviour until the additional env var `DM_USE_REDIS_SESSION_TYPE` is set.

Bump utils

---

requirements.in
requirements.txt

https://trello.com/c/LhxN5XkG/206-nft-environment-domain-issue
A logging enhancement for CSRF error logs that we want: https://github.com/Crown-Commercial-Service/digitalmarketplace-utils/pull/711

Take patch update to utils
